name: Push (CI)

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci:
    name: Typecheck & Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }} @ ${{ github.ref }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 24.0.0
      - name: Cache NPM Packages
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            npm-${{ runner.os }}-
      - name: Cache Electron Binary
        uses: actions/cache@v4
        with:
          path: ~/.cache/electron
          key: electron-${{ runner.os }}-${{ hashFiles('app/electron/package.json') }}
          restore-keys: |
            electron-${{ runner.os }}-
      - name: Install NPM Packages
        run: npm run npm:clean-install
      - name: Typecheck (Web)
        run: npm run check:ts --workspace=web
      - name: Lint (Web)
        run: npm run check:lint --workspace=web
      - name: Svelte Check (Web)
        run: npm run check:svelte --workspace=web
      - name: Vue Type Check (Web)
        run: npm run check:vue --workspace=web
      - name: Typecheck & Lint (Electron)
        run: npm run check --workspace=app/electron
      - name: Typecheck & Lint (NW.js)
        run: npm run check --workspace=app/nw
      - name: Build Web Application
        run: npm run build --workspace=web
      - name: Build Electron Application
        run: npm run build --workspace=app/electron
